// Programmers: Gigi Li and Zain Skovron
// Course:  CS 212
// Due Date: 2/4/24
// Lab Assignment: 2
// Problem Statement: Generate 10 lottery tickets for the user and tell them the potential winning prize
// Data In: User's name
// Data Out: lottery ticket numbers, estimated jackpot, congrats user
// Credits: Zybook Section 3.3, https://stackoverflow.com/questions/12806278/double-decimal-formatting-in-java (Decimal Formatting)

import java.util.Scanner;
import java.util.Random; //imports Random class
import java.text.DecimalFormat; //imports the Decimal Format Class

class Lab2 {
    public static void main(String[] args) {
        double prize = 0; //prize amount
        Scanner input = new Scanner(System.in);

        System.out.println("CS 212 - Lab 2");
        System.out.println("This program generates 10 lottery tickets."); //purpose of program
        
        System.out.print("What's your name? "); //asks for name
        String customerName = input.nextLine().strip();

        System.out.println("How much do you want to play? "); //asks how much they want to spend
        //1 raised to any power is always 1 - corner case
        //if they want to buy 10 tickets for $1, all they are getting back is the same dollar (defeats the purpose of gambling)
        double amount = input.nextFloat();
        double baseAmount = amount;

        DecimalFormat df = new DecimalFormat();
        df.setMaximumFractionDigits(2); //sets the amount to only 2 decimal digits

        System.out.println("Great! "+ customerName + " wants to play $" + df.format(amount)); //tells user how much they added

        Random rand = new Random(); //number generator

        //creates 10 lines of 6 random lottery ticket numbers
        for (int n=0; n<=9; n++){
            for (int i=0; i<=5; i++) {
                int lottery = rand.nextInt(100); //creates a random number 0-99
                if (lottery==3 || lottery==5 || lottery==16 || lottery==58 || lottery==59|| lottery==11){
                   amount = Math.pow(amount, 1.75);
                }
                String lotteryNum;
                if (lottery < 10) {
                    lotteryNum = "0" + lottery;
                } else {
                    lotteryNum = String.valueOf(lottery); //typecasts integer of lottery to String generated by IntelliJ
                }
                System.out.print(lotteryNum + " "); //prints the numbers side by side
            }
            System.out.println(""); //splits the line after 6 values
        }
        if (amount > baseAmount){ //no winning numbers = no change in amount = no winnings
            prize = amount; 
        }

        DecimalFormat formatter = new DecimalFormat("###,###,###.##"); //creates the number format

        //congrats user
        System.out.println("- - - - - - - - - - - - - - - - -");
        System.out.println("Good luck " + customerName + "!");
        System.out.println("Your winnings are:");
        System.out.println("$" + formatter.format(prize));
        System.out.println("- - - - - - - - - - - - - - - - -");

    }
}
